package de.caluga.test.mongo.suite.gui;

import de.caluga.morphium.MongoDbMode;
import de.caluga.morphium.Morphium;
import de.caluga.morphium.MorphiumConfig;
import de.caluga.morphium.gui.recordtable.RecordTable;
import de.caluga.morphium.gui.recordtable.RecordTableState;
import de.caluga.morphium.secure.DefaultSecurityManager;

import javax.swing.*;
import java.awt.*;

/**
 * User: Stpehan Bösebeck
 * Date: 26.02.12
 * Time: 17:29
 * <p/>
 * TODO: Add documentation here
 */
public class TestRT {
    private JPanel panel1;
    private RecordTableState<TestObject> state;
    private RecordTable<TestObject> recordTable1;

    private void createUIComponents() {
        state = new RecordTableState<TestObject>(TestObject.class);
        state.setSearchable(true);

        state.setFieldsToShow(Morphium.get().getFields(TestObject.class));
        state.setPreCacheAll(false);
        recordTable1 = new RecordTable<TestObject>(TestObject.class, state);
    }

    public static void main(String[] args) throws Exception {
        MorphiumConfig cfg = new MorphiumConfig("testdb", MongoDbMode.SINGLE, 5, 50000, 5000, new DefaultSecurityManager(), "logging_test.properties");
        cfg.addAddress("localhost", 27017);
        cfg.setWriteCacheTimeout(100);


        Morphium.get();
        JFrame frame = new JFrame("TestRT");
        frame.setContentPane(new TestRT().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.add(recordTable1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
