/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestObjectPanel.java
 *
 * Created on 12.09.2011, 19:18:42
 */
package de.caluga.test.mongo.suite.gui;

import de.caluga.morphium.gui.recordedit.RecordEditPanel;
import de.caluga.morphium.gui.recordedit.UpdateException;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * @author stephan
 */
public class TestObjectPanel extends RecordEditPanel<TestObject> {

    /**
     * Creates new form TestObjectPanel
     */
    public TestObjectPanel() {
        initComponents();
        counterSl.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent ce) {
                slValue.setText("" + counterSl.getValue());
                slValue.invalidate();
                slValue.repaint();
            }
        });

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataTF = new javax.swing.JTextField();
        testTF = new javax.swing.JTextField();
        blaTF = new javax.swing.JTextField();
        counterSl = new javax.swing.JSlider();
        slValue = new javax.swing.JLabel();

        jLabel1.setText("Data");

        jLabel2.setText("Tests");

        jLabel3.setText("Bla");

        jLabel4.setText("Counter");

        counterSl.setMaximum(250);
        counterSl.setMinorTickSpacing(10);
        counterSl.setPaintLabels(true);
        counterSl.setPaintTicks(true);
        counterSl.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }

            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                counterSlCaretPositionChanged(evt);
            }
        });
        counterSl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sliderMove(evt);
            }
        });
        counterSl.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt) throws java.beans.PropertyVetoException {
                vchange(evt);
            }
        });

        slValue.setText("000");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(layout.createSequentialGroup()
                                                .add(45, 45, 45)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(jLabel3)
                                                        .add(jLabel2)
                                                        .add(jLabel1))
                                                .add(18, 18, 18)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                        .add(dataTF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                                        .add(testTF)
                                                        .add(blaTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 296, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .add(layout.createSequentialGroup()
                                                .add(37, 37, 37)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(jLabel4)
                                                        .add(slValue))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(counterSl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(47, 47, 47)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel1)
                                        .add(dataTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(30, 30, 30)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel2)
                                        .add(testTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(31, 31, 31)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel3)
                                        .add(blaTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(28, 28, 28)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                                .add(jLabel4)
                                                .add(18, 18, 18)
                                                .add(slValue))
                                        .add(counterSl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sliderMove(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sliderMove
    }//GEN-LAST:event_sliderMove

    private void vchange(java.beans.PropertyChangeEvent evt) throws java.beans.PropertyVetoException {//GEN-FIRST:event_vchange
    }//GEN-LAST:event_vchange

    private void counterSlCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_counterSlCaretPositionChanged
    }//GEN-LAST:event_counterSlCaretPositionChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField blaTF;
    private javax.swing.JSlider counterSl;
    private javax.swing.JTextField dataTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel slValue;
    private javax.swing.JTextField testTF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateRecord() throws UpdateException {
//        throw new UnsupportedOperationException("Not supported yet.");
        if (!blaTF.getText().trim().equals("")) {
            getRecord().setBla(blaTF.getText());
        }
        if (counterSl.getValue() > 0) {
            getRecord().setCounter(counterSl.getValue());
        }
        if (!dataTF.getText().trim().equals("")) {
            getRecord().setData(dataTF.getText());
        }
        if (!testTF.getText().trim().equals("")) {
            getRecord().setTest(testTF.getText());
        }
    }

    @Override
    public void updateView() {
//        throw new UnsupportedOperationException("Not supported yet.");
        blaTF.setText(getRecord().getBla());
        dataTF.setText(getRecord().getData());
        counterSl.setValue(getRecord().getCounter());
        testTF.setText(getRecord().getTest());
    }
}
