package de.caluga.morphium;

/**
 * User: Stephan Bösebeck
 * Date: 05.07.12
 * Time: 13:21
 * <p/>
 */
public enum StatisticKeys {

    WRITES, WRITES_CACHED, READS, CHITS, CMISS, NO_CACHED_READS, CHITSPERC, CMISSPERC, CACHE_ENTRIES, REGISTERED_LOGGERS, WRITE_BUFFER_ENTRIES,
    PULL, PULLSKIP, SKIPPED_MSG_UPDATES, INSTANCE_COUNT
}
