package de.caluga.morphium.data;

import de.caluga.morphium.Morphium;
import de.caluga.morphium.query.Query;
import jakarta.data.Order;
import jakarta.data.Sort;
import jakarta.data.page.CursoredPage;
import jakarta.data.page.Page;
import jakarta.data.page.PageRequest;
import jakarta.data.page.impl.CursoredPageRecord;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.Executor;
import java.util.stream.Stream;

/**
 * Framework-agnostic base class for repository implementations.
 * <p>
 * Contains all CRUD, pagination and query logic as regular Java methods ({@code doXxx()}).
 * A repository interface annotated with Jakarta Data's {@code @Repository} is not implemented
 * by hand; instead, a generated or proxied implementation extends this class and forwards each
 * interface method to the matching {@code doXxx()} method here. This keeps the actual business
 * logic in plain, testable Java code and out of generated bytecode or dynamic proxies.
 * <p>
 * Role in the processing chain: interface method calls arrive here (or at {@link QueryMethodBridge},
 * {@link FindMethodBridge}, {@link JdqlMethodBridge} for derived, {@code @Find}, and {@code @Query}
 * methods respectively), which use {@link #getMorphium()} and {@link #getMetadata()} to build and
 * run a {@link Query} against MongoDB. The {@code doXxx()} methods declared directly on this class
 * cover the plain {@code CrudRepository} operations that do not require parsing (find by id,
 * find all, save, insert, update, delete, paging, cursoring).
 * <p>
 * The single most important design decision of this module is how the {@link Morphium} instance
 * reaches the repository: {@link #setMorphium(Morphium)} is the sole extension point for this.
 * Framework adapters bridge their own dependency injection to it:
 * <ul>
 *   <li>A Quarkus CDI adapter injects the {@code Morphium} bean via {@code @Inject} and calls
 *       {@code setMorphium(morphium)} from a {@code @PostConstruct} method (or overrides
 *       {@code setMorphium} itself to react to the injection).</li>
 *   <li>A Spring adapter exposes a public setter that delegates to {@code setMorphium}, so Spring's
 *       dependency injection (constructor or setter injection) can populate the field.</li>
 * </ul>
 * No other part of this module depends on a specific DI framework; only this one method needs to
 * be overridden or called by each framework-specific integration.
 * <p>
 * Example of a generated subclass (simplified):
 * <pre>{@code
 * public class ProductRepositoryImpl extends AbstractMorphiumRepository<Product, String>
 *         implements ProductRepository {
 *
 *     public ProductRepositoryImpl(RepositoryMetadata metadata) {
 *         super(metadata);
 *     }
 *
 *     // Quarkus-style bridging of CDI injection to the extension point:
 *     @Inject
 *     Morphium morphium;
 *
 *     @PostConstruct
 *     void init() {
 *         setMorphium(morphium);
 *     }
 *
 *     @Override
 *     public Optional<Product> findById(String id) {
 *         return doFindById(id);
 *     }
 * }
 * }</pre>
 *
 * @param <T> the entity type
 * @param <K> the primary-key type
 */
public abstract class AbstractMorphiumRepository<T, K> {

    private Morphium morphium;

    private final RepositoryMetadata metadata;

    protected AbstractMorphiumRepository(RepositoryMetadata metadata) {
        this.metadata = metadata;
    }

    // -- accessors for subclasses and QueryExecutor --------------------------

    /**
     * Returns the {@link Morphium} instance used to run queries and CRUD operations.
     * Populated by {@link #setMorphium(Morphium)}.
     *
     * @return the Morphium instance, or {@code null} if it has not been injected yet
     */
    public Morphium getMorphium() {
        return morphium;
    }

    /**
     * Central extension point for wiring dependency injection into this repository.
     * <p>
     * This class is deliberately framework-agnostic and has no dependency on CDI, Spring, or any
     * other injection mechanism. Framework-specific integrations bridge their own injection to this
     * method: a Quarkus adapter typically injects {@code Morphium} via {@code @Inject} and calls
     * this method from a {@code @PostConstruct} lifecycle callback (or overrides this method to be
     * notified directly), while a Spring adapter exposes a public setter that delegates here so that
     * Spring's constructor or setter injection can populate the instance. Overriding or calling this
     * method is the only integration point framework adapters need.
     *
     * @param morphium the Morphium instance to use for all subsequent operations
     */
    protected void setMorphium(Morphium morphium) {
        this.morphium = morphium;
    }

    /**
     * Returns the build-time metadata (entity class, id class, id field name) for this repository.
     *
     * @return the repository metadata
     */
    public RepositoryMetadata getMetadata() {
        return metadata;
    }

    /**
     * Returns the entity type managed by this repository, as declared in {@link #getMetadata()}.
     *
     * @return the entity class
     */
    @SuppressWarnings("unchecked")
    public Class<T> entityClass() {
        return (Class<T>) metadata.entityClass();
    }

    // -- BasicRepository CRUD operations -------------------------------------

    /**
     * Finds a single entity by its primary key.
     *
     * @param id the primary key value
     * @return an {@link Optional} containing the entity, or {@link Optional#empty()} if not found
     */
    @SuppressWarnings("unchecked")
    public Optional<T> doFindById(K id) {
        T result = (T) morphium.findById(entityClass(), id, null);
        return Optional.ofNullable(result);
    }

    /**
     * Streams all entities of this repository's type.
     *
     * @return a stream over all entities
     */
    public Stream<T> doFindAll() {
        return morphium.createQueryFor(entityClass()).stream();
    }

    /**
     * Finds all entities as an offset-based {@link Page}, applying the given sort order.
     *
     * @param pageRequest the requested page (offset, size, whether to compute the total count)
     * @param sortBy      the sort order to apply, may be {@code null} or empty for no explicit sort
     * @return the requested page of entities
     */
    @SuppressWarnings("unchecked")
    public Page<T> doFindAllPaged(PageRequest pageRequest, Order<T> sortBy) {
        Query<T> query = morphium.createQueryFor(entityClass());

        // Apply sorting from Order
        if (sortBy != null && !sortBy.sorts().isEmpty()) {
            Map<String, Integer> sortMap = new LinkedHashMap<>();
            for (Sort<? super T> sort : sortBy.sorts()) {
                String mongoField = resolveMongoField(sort.property());
                sortMap.put(mongoField, sort.isAscending() ? 1 : -1);
            }
            query.sort(sortMap);
        }

        // Apply pagination
        int size = pageRequest.size();
        long page = pageRequest.page();
        int skip = (int) ((page - 1) * size);
        query.skip(skip).limit(size);

        List<T> content = query.asList();

        // Total count (only if requested)
        long totalElements = -1;
        if (pageRequest.requestTotal()) {
            totalElements = morphium.createQueryFor(entityClass()).countAll();
        }

        return new MorphiumPage<>(content, totalElements, pageRequest);
    }

    /**
     * Finds all entities as a keyset (cursor-based) {@link CursoredPage}, applying the given sort
     * order. Delegates cursor-condition and cursor-extraction logic to {@link CursorHelper}.
     *
     * @param pageRequest the requested page (cursor/offset mode, size, whether to compute the total count)
     * @param sortBy      the sort order defining the keyset fields, may be {@code null} or empty
     * @return the requested cursored page of entities
     * @throws IllegalArgumentException if {@code pageRequest} requires a cursor but none is present
     */
    @SuppressWarnings("unchecked")
    public CursoredPage<T> doFindAllCursored(PageRequest pageRequest, Order<T> sortBy) {
        Query<T> query = morphium.createQueryFor(entityClass());

        // Build sort specs from Order
        List<CursorHelper.SortSpec> sortSpecs = new ArrayList<>();
        if (sortBy != null && !sortBy.sorts().isEmpty()) {
            for (Sort<? super T> sort : sortBy.sorts()) {
                sortSpecs.add(new CursorHelper.SortSpec(sort.property(), sort.isAscending()));
            }
        }

        boolean isForward = pageRequest.mode() != PageRequest.Mode.CURSOR_PREVIOUS;

        if (pageRequest.mode() != PageRequest.Mode.OFFSET) {
            PageRequest.Cursor cursor = pageRequest.cursor()
                    .orElseThrow(() -> new IllegalArgumentException(
                            "PageRequest mode is " + pageRequest.mode() + " but no cursor provided"));
            CursorHelper.applyCursorCondition(query, cursor, sortSpecs, morphium, entityClass(), isForward);
        }

        CursorHelper.applySort(query, sortSpecs, morphium, entityClass(), isForward);
        int requestedSize = pageRequest.size();
        query.limit(requestedSize + 1);

        List<T> content = query.asList();
        boolean hasMore = content.size() > requestedSize;
        if (hasMore) {
            content = new ArrayList<>(content.subList(0, requestedSize));
        }
        if (!isForward) {
            Collections.reverse(content);
        }

        List<String> sortFields = sortSpecs.stream().map(CursorHelper.SortSpec::javaField).toList();
        List<PageRequest.Cursor> cursors = CursorHelper.extractCursors(content, sortFields, morphium, entityClass());

        long totalElements = -1;
        if (pageRequest.requestTotal()) {
            totalElements = morphium.createQueryFor(entityClass()).countAll();
        }

        boolean isFirstPage = pageRequest.mode() == PageRequest.Mode.OFFSET;
        boolean isLastPage = !hasMore;

        if (content.isEmpty()) {
            return new CursoredPageRecord<>(content, cursors, totalElements, pageRequest,
                    (PageRequest) null, (PageRequest) null);
        }

        return new CursoredPageRecord<>(content, cursors, totalElements, pageRequest,
                isFirstPage, isLastPage);
    }

    /**
     * Saves (upserts) a single entity via {@code Morphium.store()}.
     *
     * @param entity the entity to save
     * @return the same entity instance
     */
    public Object doSave(Object entity) {
        morphium.store(entity);
        return entity;
    }

    /**
     * Saves (upserts) a list of entities via {@code Morphium.storeList()}.
     *
     * @param entities the entities to save
     * @return the same list of entities
     */
    @SuppressWarnings("unchecked")
    public List<Object> doSaveAll(List<?> entities) {
        morphium.storeList((List) entities);
        return (List<Object>) entities;
    }

    /**
     * Inserts a single new entity via {@code Morphium.insert()}.
     *
     * @param entity the entity to insert
     * @return the same entity instance
     */
    public Object doInsert(Object entity) {
        morphium.insert(entity);
        return entity;
    }

    /**
     * Inserts a list of new entities via {@code Morphium.insertList()}.
     *
     * @param entities the entities to insert
     * @return the same list of entities
     */
    @SuppressWarnings("unchecked")
    public List<Object> doInsertAll(List<?> entities) {
        morphium.insertList((List) entities);
        return (List<Object>) entities;
    }

    /**
     * Updates a single entity via {@code Morphium.store()}.
     *
     * @param entity the entity to update
     * @return the same entity instance
     */
    public Object doUpdate(Object entity) {
        morphium.store(entity);
        return entity;
    }

    /**
     * Updates a list of entities via {@code Morphium.storeList()}.
     *
     * @param entities the entities to update
     * @return the same list of entities
     */
    @SuppressWarnings("unchecked")
    public List<Object> doUpdateAll(List<?> entities) {
        morphium.storeList((List) entities);
        return (List<Object>) entities;
    }

    /**
     * Deletes a single entity via {@code Morphium.delete()}.
     *
     * @param entity the entity to delete
     */
    public void doDelete(Object entity) {
        morphium.delete(entity);
    }

    /**
     * Deletes a single entity by its primary key, loading it first. Does nothing if no
     * entity with the given id exists.
     *
     * @param id the primary key of the entity to delete
     */
    @SuppressWarnings("unchecked")
    public void doDeleteById(K id) {
        T entity = (T) morphium.findById(entityClass(), id, null);
        if (entity != null) {
            morphium.delete(entity);
        }
    }

    /**
     * Deletes each entity in the given list via {@code Morphium.delete()}.
     *
     * @param entities the entities to delete
     */
    @SuppressWarnings("unchecked")
    public void doDeleteAll(List<?> entities) {
        for (Object entity : entities) {
            morphium.delete(entity);
        }
    }

    /**
     * Deletes all entities of this repository's type by clearing the entire collection.
     */
    public void doDeleteAllNoArg() {
        morphium.clearCollection(entityClass());
    }

    /**
     * Creates a new, unrestricted Morphium {@link Query} for this repository's entity type.
     *
     * @return a new query instance
     */
    public Query<T> createQuery() {
        return morphium.createQueryFor(entityClass());
    }

    // -- MorphiumRepository operations ----------------------------------------

    /**
     * Returns distinct values for the given Java field name across all entities.
     *
     * @param fieldName the Java field name (resolved to the MongoDB field name)
     * @return the distinct values found for the field
     */
    @SuppressWarnings("unchecked")
    public List<Object> doDistinct(String fieldName) {
        String mongoField = resolveMongoField(fieldName);
        return (List<Object>) (List<?>) morphium.createQueryFor(entityClass()).distinct(mongoField);
    }

    /**
     * Returns the underlying {@link Morphium} instance, for escape-hatch operations that have
     * no Jakarta Data equivalent (aggregations, atomic updates, etc.).
     *
     * @return the Morphium instance
     */
    public Morphium doMorphium() {
        return morphium;
    }

    /**
     * Creates a new, unrestricted Morphium {@link Query} for this repository's entity type.
     * Equivalent to {@link #createQuery()}, exposed under the name used by
     * {@link MorphiumRepository#query()}.
     *
     * @return a new query instance
     */
    public Query<T> doQuery() {
        return morphium.createQueryFor(entityClass());
    }

    /**
     * Resolves a Java field name to its MongoDB field name via the Morphium annotation/reflection
     * helper, falling back to the Java field name itself if resolution fails.
     *
     * @param javaFieldName the Java field name
     * @return the MongoDB field name, or {@code javaFieldName} if it cannot be resolved
     */
    @SuppressWarnings("unchecked")
    private String resolveMongoField(String javaFieldName) {
        try {
            return morphium.getARHelper().getMongoFieldName(entityClass(), javaFieldName);
        } catch (Exception e) {
            return javaFieldName;
        }
    }

    // -- Async support --------------------------------------------------------

    /**
     * Returns the executor used for the {@code doXxxAsync()} methods, backed by Morphium's
     * async operations thread pool.
     *
     * @return the async executor
     */
    public Executor getAsyncExecutor() {
        return morphium.getAsyncOperationsThreadPool();
    }

    /**
     * Asynchronous variant of {@link #doFindById(Object)}.
     *
     * @param id the primary key value
     * @return a completion stage yielding the result of {@link #doFindById(Object)}
     */
    public CompletionStage<Optional<T>> doFindByIdAsync(K id) {
        return CompletableFuture.supplyAsync(() -> doFindById(id), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doFindAll()}.
     *
     * @return a completion stage yielding the result of {@link #doFindAll()}
     */
    public CompletionStage<Stream<T>> doFindAllAsync() {
        return CompletableFuture.supplyAsync(this::doFindAll, getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doSave(Object)}.
     *
     * @param entity the entity to save
     * @return a completion stage yielding the result of {@link #doSave(Object)}
     */
    public CompletionStage<Object> doSaveAsync(Object entity) {
        return CompletableFuture.supplyAsync(() -> doSave(entity), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doSaveAll(List)}.
     *
     * @param entities the entities to save
     * @return a completion stage yielding the result of {@link #doSaveAll(List)}
     */
    public CompletionStage<List<Object>> doSaveAllAsync(List<?> entities) {
        return CompletableFuture.supplyAsync(() -> doSaveAll(entities), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doInsert(Object)}.
     *
     * @param entity the entity to insert
     * @return a completion stage yielding the result of {@link #doInsert(Object)}
     */
    public CompletionStage<Object> doInsertAsync(Object entity) {
        return CompletableFuture.supplyAsync(() -> doInsert(entity), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doInsertAll(List)}.
     *
     * @param entities the entities to insert
     * @return a completion stage yielding the result of {@link #doInsertAll(List)}
     */
    public CompletionStage<List<Object>> doInsertAllAsync(List<?> entities) {
        return CompletableFuture.supplyAsync(() -> doInsertAll(entities), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doUpdate(Object)}.
     *
     * @param entity the entity to update
     * @return a completion stage yielding the result of {@link #doUpdate(Object)}
     */
    public CompletionStage<Object> doUpdateAsync(Object entity) {
        return CompletableFuture.supplyAsync(() -> doUpdate(entity), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doUpdateAll(List)}.
     *
     * @param entities the entities to update
     * @return a completion stage yielding the result of {@link #doUpdateAll(List)}
     */
    public CompletionStage<List<Object>> doUpdateAllAsync(List<?> entities) {
        return CompletableFuture.supplyAsync(() -> doUpdateAll(entities), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doDelete(Object)}.
     *
     * @param entity the entity to delete
     * @return a completion stage that completes when the deletion finishes
     */
    public CompletionStage<Void> doDeleteAsync(Object entity) {
        return CompletableFuture.runAsync(() -> doDelete(entity), getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #doDeleteById(Object)}.
     *
     * @param id the primary key of the entity to delete
     * @return a completion stage that completes when the deletion finishes
     */
    public CompletionStage<Void> doDeleteByIdAsync(K id) {
        return CompletableFuture.runAsync(() -> doDeleteById(id), getAsyncExecutor());
    }
}
