package de.caluga.morphium.data;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Runtime bridge called by Gizmo-generated repository methods for query derivation.
 * <p>
 * The build-time annotation processor generates a call from each repository interface method
 * (e.g. {@code findByStatus(String status)}) into {@link #executeQuery}, passing the method name
 * and arguments as plain runtime values instead of generating query-building bytecode. This class
 * parses the method name via {@link MethodNameParser#parse} (caching the resulting
 * {@link QueryDescriptor} per entity type and method), adjusts the descriptor's return type to
 * match the caller's declared return shape, merges any {@code @OrderBy} annotation spec, and
 * finally delegates execution to {@link QueryExecutor#execute}. This is the derived-query
 * counterpart of {@link FindMethodBridge} ({@code @Find} methods) and {@link JdqlMethodBridge}
 * ({@code @Query}/JDQL methods).
 */
public final class QueryMethodBridge {

    private static final ConcurrentHashMap<String, QueryDescriptor> CACHE = new ConcurrentHashMap<>();

    private QueryMethodBridge() {}

    /**
     * Called from generated bytecode for each derived query method invocation.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @return the query result
     */
    public static Object executeQuery(AbstractMorphiumRepository<?, ?> repo,
                                      String methodName,
                                      Object[] args,
                                      boolean returnsSingle,
                                      boolean returnsOptional,
                                      boolean returnsBoolean,
                                      boolean returnsStream) {
        return executeQuery(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream, "");
    }

    /**
     * Called from generated bytecode for each derived query method invocation.
     * Overload that accepts an {@code @OrderBy} annotation spec to merge with
     * any method-name-derived ordering.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @param orderBySpec     the {@code @OrderBy} annotation spec (e.g. "createdAt:DESC")
     * @return the query result
     */
    public static Object executeQuery(AbstractMorphiumRepository<?, ?> repo,
                                      String methodName,
                                      Object[] args,
                                      boolean returnsSingle,
                                      boolean returnsOptional,
                                      boolean returnsBoolean,
                                      boolean returnsStream,
                                      String orderBySpec) {
        String cacheKey = repo.getMetadata().entityClass().getName() + "#" + methodName
                + (orderBySpec.isEmpty() ? "" : "#" + orderBySpec);

        QueryDescriptor descriptor = CACHE.computeIfAbsent(cacheKey, k -> {
            QueryDescriptor parsed = MethodNameParser.parse(methodName, null);

            // Merge method-name-derived OrderBy with @OrderBy annotation specs
            if (!orderBySpec.isEmpty()) {
                var mergedOrderBy = new ArrayList<>(parsed.orderBy());
                mergedOrderBy.addAll(parseOrderBySpec(orderBySpec));
                return new QueryDescriptor(
                        parsed.prefix(),
                        parsed.conditions(),
                        parsed.combinator(),
                        mergedOrderBy,
                        parsed.returnType());
            }
            return parsed;
        });

        // Override return type if caller expects single, optional, or stream result
        if (descriptor.prefix() == QueryDescriptor.Prefix.FIND) {
            if (returnsOptional) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.OPTIONAL);
            } else if (returnsSingle) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.SINGLE);
            } else if (returnsStream) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.STREAM);
            }
        }

        Object result = QueryExecutor.execute(descriptor, args, repo);

        // For deleteBy* with boolean return: convert count > 0
        if (returnsBoolean && result instanceof Long count) {
            return count > 0;
        }

        return result;
    }

    /**
     * Asynchronous variant of {@link #executeQuery(AbstractMorphiumRepository, String, Object[],
     * boolean, boolean, boolean, boolean)}, running the query on the repository's async executor.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @return a completion stage yielding the query result
     */
    public static CompletionStage<Object> executeQueryAsync(AbstractMorphiumRepository<?, ?> repo,
                                                             String methodName,
                                                             Object[] args,
                                                             boolean returnsSingle,
                                                             boolean returnsOptional,
                                                             boolean returnsBoolean,
                                                             boolean returnsStream) {
        return executeQueryAsync(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream, "");
    }

    /**
     * Asynchronous variant of {@link #executeQuery(AbstractMorphiumRepository, String, Object[],
     * boolean, boolean, boolean, boolean, String)}, running the query on the repository's async
     * executor.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @param orderBySpec     the {@code @OrderBy} annotation spec (e.g. "createdAt:DESC")
     * @return a completion stage yielding the query result
     */
    public static CompletionStage<Object> executeQueryAsync(AbstractMorphiumRepository<?, ?> repo,
                                                             String methodName,
                                                             Object[] args,
                                                             boolean returnsSingle,
                                                             boolean returnsOptional,
                                                             boolean returnsBoolean,
                                                             boolean returnsStream,
                                                             String orderBySpec) {
        return CompletableFuture.supplyAsync(
                () -> executeQuery(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream, orderBySpec),
                repo.getAsyncExecutor());
    }

    /**
     * Parses the build-time orderBy spec string (e.g. "createdAt:DESC,name:ASC")
     * into a list of {@link QueryDescriptor.OrderSpec}.
     */
    private static List<QueryDescriptor.OrderSpec> parseOrderBySpec(String spec) {
        var result = new ArrayList<QueryDescriptor.OrderSpec>();
        for (String part : spec.split(",")) {
            String trimmed = part.trim();
            if (trimmed.isEmpty()) {
                throw new IllegalArgumentException("Empty fragment in @OrderBy spec: '" + spec + "'");
            }
            String[] fieldAndDir = trimmed.split(":", -1);
            if (fieldAndDir.length > 2) {
                throw new IllegalArgumentException("Invalid @OrderBy fragment: '" + trimmed + "'");
            }
            String field = fieldAndDir[0].trim();
            if (field.isEmpty()) {
                throw new IllegalArgumentException("Empty field name in @OrderBy spec: '" + spec + "'");
            }
            if (fieldAndDir.length > 1) {
                String dirStr = fieldAndDir[1].trim();
                if (!"ASC".equals(dirStr) && !"DESC".equals(dirStr)) {
                    throw new IllegalArgumentException(
                            "Invalid direction '" + dirStr + "' in @OrderBy spec: '" + spec
                                    + "' — expected ASC or DESC");
                }
            }
            QueryDescriptor.Direction dir = fieldAndDir.length > 1 && "DESC".equals(fieldAndDir[1].trim())
                    ? QueryDescriptor.Direction.DESC : QueryDescriptor.Direction.ASC;
            result.add(new QueryDescriptor.OrderSpec(field, dir));
        }
        return result;
    }
}
