package de.caluga.morphium.data;

import de.caluga.morphium.Morphium;
import de.caluga.morphium.query.Query;
import jakarta.data.Limit;
import jakarta.data.Order;
import jakarta.data.Sort;
import jakarta.data.page.PageRequest;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Runtime bridge called by Gizmo-generated repository methods for query derivation.
 * <p>
 * The build-time annotation processor generates a call from each repository interface method
 * (e.g. {@code findByStatus(String status)}) into {@link #executeQuery}, passing the method name
 * and arguments as plain runtime values instead of generating query-building bytecode. This class
 * parses the method name via {@link MethodNameParser#parse} (caching the resulting
 * {@link QueryDescriptor} per entity type and method), adjusts the descriptor's return type to
 * match the caller's declared return shape, merges any {@code @OrderBy} annotation spec, and
 * finally delegates execution to {@link QueryExecutor#execute}. This is the derived-query
 * counterpart of {@link FindMethodBridge} ({@code @Find} methods) and {@link JdqlMethodBridge}
 * ({@code @Query}/JDQL methods).
 */
public final class QueryMethodBridge {

    private static final ConcurrentHashMap<String, QueryDescriptor> CACHE = new ConcurrentHashMap<>();

    private QueryMethodBridge() {}

    /**
     * Called from generated bytecode for each derived query method invocation.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @return the query result
     */
    public static Object executeQuery(AbstractMorphiumRepository<?, ?> repo,
                                      String methodName,
                                      Object[] args,
                                      boolean returnsSingle,
                                      boolean returnsOptional,
                                      boolean returnsBoolean,
                                      boolean returnsStream) {
        return executeQuery(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream, "");
    }

    /**
     * Called from generated bytecode for each derived query method invocation that declares a
     * dynamic {@code Sort}, {@code Order}, {@code PageRequest}, or {@code Limit} parameter.
     * Unlike the simpler overloads above (which delegate entirely to {@link QueryExecutor#execute}
     * and support only method-name-derived and {@code @OrderBy}-annotation-derived ordering),
     * this overload builds the query itself so a dynamic parameter can be applied on top: a
     * {@code Sort}/{@code Order} argument overrides the parsed ordering (mirroring how
     * {@link FindMethodBridge#executeFind} treats a dynamic {@code Sort}/{@code Order} argument as
     * taking precedence over a static {@code @OrderBy}), a {@code Limit} argument applies
     * {@code skip}/{@code limit}, and a {@code PageRequest} argument returns a {@link MorphiumPage}
     * instead of the plain result shape.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @param orderBySpec     the {@code @OrderBy} annotation spec (e.g. "createdAt:DESC"), "" for none
     * @param sortParamIndex     index of a {@code Sort} parameter, -1 if absent
     * @param orderParamIndex    index of an {@code Order} parameter, -1 if absent
     * @param pageRequestParamIndex index of a {@code PageRequest} parameter, -1 if absent
     * @param limitParamIndex    index of a {@code Limit} parameter, -1 if absent
     * @return the query result
     */
    @SuppressWarnings({"unchecked", "rawtypes"})
    public static Object executeQuery(AbstractMorphiumRepository<?, ?> repo,
                                      String methodName,
                                      Object[] args,
                                      boolean returnsSingle,
                                      boolean returnsOptional,
                                      boolean returnsBoolean,
                                      boolean returnsStream,
                                      String orderBySpec,
                                      int sortParamIndex,
                                      int orderParamIndex,
                                      int pageRequestParamIndex,
                                      int limitParamIndex) {
        if (sortParamIndex < 0 && orderParamIndex < 0 && pageRequestParamIndex < 0 && limitParamIndex < 0) {
            // No dynamic parameter present -- identical to the simpler overload, avoids
            // building the query twice (once here, once inside QueryExecutor.execute).
            return executeQuery(repo, methodName, args, returnsSingle, returnsOptional,
                    returnsBoolean, returnsStream, orderBySpec);
        }

        String cacheKey = repo.getMetadata().entityClass().getName() + "#" + methodName
                + (orderBySpec.isEmpty() ? "" : "#" + orderBySpec);
        QueryDescriptor descriptor = CACHE.computeIfAbsent(cacheKey, k -> {
            QueryDescriptor parsed = MethodNameParser.parse(methodName, null);
            if (!orderBySpec.isEmpty()) {
                var mergedOrderBy = new ArrayList<>(parsed.orderBy());
                mergedOrderBy.addAll(parseOrderBySpec(orderBySpec));
                return new QueryDescriptor(parsed.prefix(), parsed.conditions(),
                        parsed.combinator(), mergedOrderBy, parsed.returnType());
            }
            return parsed;
        });

        // Regression fix (see commit 11f669e77 review, PR #267): this overload used to always
        // fall through to a plain find (query.asList()/asBoolean-from-list-emptiness) further
        // down, no matter what descriptor.prefix() said. That is correct for FIND, but for
        // COUNT/EXISTS/DELETE it silently turned a countBy*/existsBy*/deleteBy* method with a
        // dynamic Sort/Order/PageRequest/Limit parameter into a find: countBy*/existsBy* got a
        // List back where a Long/boolean was expected (ClassCastException at the generated
        // checkCast), and deleteBy* stopped deleting anything at all while still reporting
        // success.
        //
        // Decision: for any non-FIND prefix, delegate to the same QueryExecutor.execute() path
        // used by the simpler (no-dynamic-parameter) overload below, which already implements
        // the correct DELETE/COUNT/EXISTS semantics (actually deletes, returns a count/boolean,
        // never a List). This *does* take the dynamic parameters into account: a dynamic
        // Sort/Order argument is harmless to accept-and-ignore here (there is no result set on a
        // count, an existence check, or a bulk delete for it to reorder — same reasoning as a
        // static/method-name-derived order-by, which QueryExecutor.execute() already applies
        // only for FIND), so simply not passing it through is the correct, side-effect-free
        // behaviour. A dynamic Limit or PageRequest argument on a non-FIND prefix, however, is
        // semantically questionable (what would "the 3rd page of a delete" or "count, but only
        // the first 10" mean?) and is not sensibly supportable — that combination is therefore
        // rejected at BUILD TIME in MorphiumDataProcessor.generateQueryMethod(), so it can never
        // reach this method; if it ever did, it would be silently ignored below, same as Sort/
        // Order, since limitParamIndex/pageRequestParamIndex are simply not read on this branch.
        if (descriptor.prefix() != QueryDescriptor.Prefix.FIND) {
            Object result = QueryExecutor.execute(descriptor, args, repo);
            // For deleteBy* with boolean return: convert count > 0 (mirrors the equivalent
            // conversion in the simpler overload below).
            if (returnsBoolean && result instanceof Long count) {
                return count > 0;
            }
            return result;
        }

        Morphium morphium = repo.getMorphium();
        Class entityClass = repo.getMetadata().entityClass();
        Query query = morphium.createQueryFor(entityClass);
        QueryExecutor.applyConditions(query, descriptor, args, morphium, entityClass);

        // Static (method-name-derived / @OrderBy) ordering first -- a dynamic Sort/Order
        // argument below overrides it, same precedence as FindMethodBridge.executeFind.
        if (descriptor.orderBy() != null && !descriptor.orderBy().isEmpty()) {
            QueryExecutor.applySorting(query, descriptor.orderBy(), morphium, entityClass);
        }

        if (sortParamIndex >= 0 && args[sortParamIndex] != null) {
            Sort sort = (Sort) args[sortParamIndex];
            Map<String, Integer> sortMap = new LinkedHashMap<>();
            String mongoField = QueryExecutor.resolveMongoField(morphium, entityClass, sort.property());
            sortMap.put(mongoField, sort.isAscending() ? 1 : -1);
            query.sort(sortMap);
        }
        if (orderParamIndex >= 0 && args[orderParamIndex] != null) {
            Order order = (Order) args[orderParamIndex];
            if (!order.sorts().isEmpty()) {
                Map<String, Integer> sortMap = new LinkedHashMap<>();
                for (Object s : order.sorts()) {
                    Sort sort = (Sort) s;
                    String mongoField = QueryExecutor.resolveMongoField(morphium, entityClass, sort.property());
                    sortMap.put(mongoField, sort.isAscending() ? 1 : -1);
                }
                query.sort(sortMap);
            }
        }
        if (limitParamIndex >= 0 && args[limitParamIndex] != null) {
            Limit limit = (Limit) args[limitParamIndex];
            query.skip((int) (limit.startAt() - 1));
            query.limit(limit.maxResults());
        }
        if (pageRequestParamIndex >= 0 && args[pageRequestParamIndex] != null) {
            PageRequest pageRequest = (PageRequest) args[pageRequestParamIndex];
            int size = pageRequest.size();
            long page = pageRequest.page();
            int skip = (int) ((page - 1) * size);
            query.skip(skip).limit(size);

            List content = query.asList();
            long totalElements = -1;
            if (pageRequest.requestTotal()) {
                Query countQuery = morphium.createQueryFor(entityClass);
                QueryExecutor.applyConditions(countQuery, descriptor, args, morphium, entityClass);
                totalElements = countQuery.countAll();
            }
            return new MorphiumPage<>(content, totalElements, pageRequest);
        }

        if (returnsOptional) {
            return QueryResultHelper.optionalSingle(query);
        }
        if (returnsSingle) {
            return QueryResultHelper.requireSingle(query);
        }
        if (returnsStream) {
            return query.stream();
        }
        List resultList = query.asList();
        if (returnsBoolean) {
            return !resultList.isEmpty();
        }
        return resultList;
    }

    /**
     * Called from generated bytecode for each derived query method invocation.
     * Overload that accepts an {@code @OrderBy} annotation spec to merge with
     * any method-name-derived ordering.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @param orderBySpec     the {@code @OrderBy} annotation spec (e.g. "createdAt:DESC")
     * @return the query result
     */
    public static Object executeQuery(AbstractMorphiumRepository<?, ?> repo,
                                      String methodName,
                                      Object[] args,
                                      boolean returnsSingle,
                                      boolean returnsOptional,
                                      boolean returnsBoolean,
                                      boolean returnsStream,
                                      String orderBySpec) {
        String cacheKey = repo.getMetadata().entityClass().getName() + "#" + methodName
                + (orderBySpec.isEmpty() ? "" : "#" + orderBySpec);

        QueryDescriptor descriptor = CACHE.computeIfAbsent(cacheKey, k -> {
            QueryDescriptor parsed = MethodNameParser.parse(methodName, null);

            // Merge method-name-derived OrderBy with @OrderBy annotation specs
            if (!orderBySpec.isEmpty()) {
                var mergedOrderBy = new ArrayList<>(parsed.orderBy());
                mergedOrderBy.addAll(parseOrderBySpec(orderBySpec));
                return new QueryDescriptor(
                        parsed.prefix(),
                        parsed.conditions(),
                        parsed.combinator(),
                        mergedOrderBy,
                        parsed.returnType());
            }
            return parsed;
        });

        // Override return type if caller expects single, optional, or stream result
        if (descriptor.prefix() == QueryDescriptor.Prefix.FIND) {
            if (returnsOptional) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.OPTIONAL);
            } else if (returnsSingle) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.SINGLE);
            } else if (returnsStream) {
                descriptor = new QueryDescriptor(
                        descriptor.prefix(),
                        descriptor.conditions(),
                        descriptor.combinator(),
                        descriptor.orderBy(),
                        QueryDescriptor.ReturnType.STREAM);
            }
        }

        Object result = QueryExecutor.execute(descriptor, args, repo);

        // For deleteBy* with boolean return: convert count > 0
        if (returnsBoolean && result instanceof Long count) {
            return count > 0;
        }

        return result;
    }

    /**
     * Asynchronous variant of {@link #executeQuery(AbstractMorphiumRepository, String, Object[],
     * boolean, boolean, boolean, boolean)}, running the query on the repository's async executor.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @return a completion stage yielding the query result
     */
    public static CompletionStage<Object> executeQueryAsync(AbstractMorphiumRepository<?, ?> repo,
                                                             String methodName,
                                                             Object[] args,
                                                             boolean returnsSingle,
                                                             boolean returnsOptional,
                                                             boolean returnsBoolean,
                                                             boolean returnsStream) {
        return executeQueryAsync(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream, "");
    }

    /**
     * Asynchronous variant of {@link #executeQuery(AbstractMorphiumRepository, String, Object[],
     * boolean, boolean, boolean, boolean, String)}, running the query on the repository's async
     * executor.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @param orderBySpec     the {@code @OrderBy} annotation spec (e.g. "createdAt:DESC")
     * @return a completion stage yielding the query result
     */
    public static CompletionStage<Object> executeQueryAsync(AbstractMorphiumRepository<?, ?> repo,
                                                             String methodName,
                                                             Object[] args,
                                                             boolean returnsSingle,
                                                             boolean returnsOptional,
                                                             boolean returnsBoolean,
                                                             boolean returnsStream,
                                                             String orderBySpec) {
        return CompletableFuture.supplyAsync(
                () -> executeQuery(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream, orderBySpec),
                repo.getAsyncExecutor());
    }

    /**
     * Asynchronous variant of {@link #executeQuery(AbstractMorphiumRepository, String, Object[],
     * boolean, boolean, boolean, boolean, String, int, int, int, int)}, running the query on the
     * repository's async executor. Used for derived query methods that declare a dynamic
     * {@code Sort}, {@code Order}, {@code PageRequest}, or {@code Limit} parameter and a
     * {@code CompletionStage} return type.
     *
     * @param repo            the repository instance (provides Morphium + metadata)
     * @param methodName      the repository method name (e.g. "findByStatus")
     * @param args            the method arguments
     * @param returnsSingle   whether the caller expects a single result (T)
     * @param returnsOptional whether the caller expects an Optional result
     * @param returnsBoolean  whether the caller expects a boolean result (for deleteBy*)
     * @param returnsStream   whether the caller expects a Stream result
     * @param orderBySpec     the {@code @OrderBy} annotation spec (e.g. "createdAt:DESC")
     * @param sortParamIndex     index of a {@code Sort} parameter, -1 if absent
     * @param orderParamIndex    index of an {@code Order} parameter, -1 if absent
     * @param pageRequestParamIndex index of a {@code PageRequest} parameter, -1 if absent
     * @param limitParamIndex    index of a {@code Limit} parameter, -1 if absent
     * @return a completion stage yielding the query result
     */
    public static CompletionStage<Object> executeQueryAsync(AbstractMorphiumRepository<?, ?> repo,
                                                             String methodName,
                                                             Object[] args,
                                                             boolean returnsSingle,
                                                             boolean returnsOptional,
                                                             boolean returnsBoolean,
                                                             boolean returnsStream,
                                                             String orderBySpec,
                                                             int sortParamIndex,
                                                             int orderParamIndex,
                                                             int pageRequestParamIndex,
                                                             int limitParamIndex) {
        return CompletableFuture.supplyAsync(
                () -> executeQuery(repo, methodName, args, returnsSingle, returnsOptional, returnsBoolean, returnsStream,
                        orderBySpec, sortParamIndex, orderParamIndex, pageRequestParamIndex, limitParamIndex),
                repo.getAsyncExecutor());
    }

    /**
     * Parses the build-time orderBy spec string (e.g. "createdAt:DESC,name:ASC")
     * into a list of {@link QueryDescriptor.OrderSpec}.
     */
    private static List<QueryDescriptor.OrderSpec> parseOrderBySpec(String spec) {
        var result = new ArrayList<QueryDescriptor.OrderSpec>();
        for (String part : spec.split(",")) {
            String trimmed = part.trim();
            if (trimmed.isEmpty()) {
                throw new IllegalArgumentException("Empty fragment in @OrderBy spec: '" + spec + "'");
            }
            String[] fieldAndDir = trimmed.split(":", -1);
            if (fieldAndDir.length > 2) {
                throw new IllegalArgumentException("Invalid @OrderBy fragment: '" + trimmed + "'");
            }
            String field = fieldAndDir[0].trim();
            if (field.isEmpty()) {
                throw new IllegalArgumentException("Empty field name in @OrderBy spec: '" + spec + "'");
            }
            if (fieldAndDir.length > 1) {
                String dirStr = fieldAndDir[1].trim();
                if (!"ASC".equals(dirStr) && !"DESC".equals(dirStr)) {
                    throw new IllegalArgumentException(
                            "Invalid direction '" + dirStr + "' in @OrderBy spec: '" + spec
                                    + "' — expected ASC or DESC");
                }
            }
            QueryDescriptor.Direction dir = fieldAndDir.length > 1 && "DESC".equals(fieldAndDir[1].trim())
                    ? QueryDescriptor.Direction.DESC : QueryDescriptor.Direction.ASC;
            result.add(new QueryDescriptor.OrderSpec(field, dir));
        }
        return result;
    }
}
